<!DOCTYPE html>
<html lang="zh_CN">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="/faviconcompress.ico" sizes="16x16 32x32" type="image/vnd.microsoft.icon">
<title></title>
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/umeditor.min.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/intro.css">
<!--blog.css 引入要在intro.css之后 .navbar-default 有冲突-->
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/blog.css">
<!--blog_list.css 引入要在blog.css之后 .body颜色 有冲突-->
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/blog_list.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/blog_new.css">
<script src="<?php echo __STATIC_FILE__;?>/js/respond.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/html5shiv.min.js"></script>

</head>

<body>
<div class="header">
  <div class="container">
  
      	<nav role="navigation" class="navbar navbar-default">
			<div class="navbar-header">
				<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
    				<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
    			</button>
				<a class="navbar-brand" href="http://beyond.cikii.com/"><h2>Cikii</h2></a>
    		</div>
    								
    		<div id="navbar-collapse-02" class="collapse navbar-collapse">
				<ul class="nav navbar-nav headerul">
					<li><a href="http://beyond.cikii.com/blog/index/index"><h5>博客首页</h5></a></li>
					<li><a href="#"><h5>活动报名</h5></a></li>
				</ul>
				<!--
                 <form class="navbar-form navbar-left sbox">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="">
                    </div>
                    <button type="submit" class="btn btn-default">搜索一下</button>
                 </form>
				 -->
    			<ul	id="headerul" class="nav navbar-nav navbar-right">			      
                    <li class="dropdown">
                        <?php if("true" === $logged) {
                            echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><h5>'. $showname .'<span class="caret"></span></h5></a>';
                        } else {
					        echo '<li class="nav_register" role="presentation"><a href="#" data-toggle="modal" data-target="#login-modal"><h5>登录</h5></a></li>';
                        }?>

                        <ul class="dropdown-menu">

					        <?php 
					        if("true"==="$logged") {
					        echo '<li><a href="../navbar/">我的博客</a></li>';
					        echo '<li><a href="../navbar/">我的活动</a></li>';
					        echo '<li><a href="../navbar/">消息</a></li>';
                            echo '<li role="separator" class="divider"></li>';
					        echo '<li role="presentation" data-toggle="modal" data-target=".bs-example-modal-sm"><a href="#">退出</a> </li>'; 
					        } else {
					        echo '<li class="nav_register" role="presentation"><a href="#" data-toggle="modal" data-target="#login-modal">登录</a></li>';
					        } 
					        ?>
                        </ul>
                    </li>
					  
					  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
						<div class="modal-dialog modal-sm">
						  <div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title">确定要退出cikii?</h4>
						  </div>
						  <div class="modal-dialog modal-sm">
							  <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
							  <a href="http://beyond.cikii.com/user/index/logout"><button type="button" class="btn btn-primary">确定</button></a>
						  </div>
						</div>
					  </div>
    			</ul> 		      
    		</div><!-- /.navbar-collapse -->	
		<nav

    <!--登录框 -->

    <div class="modal fade" style="display:none; color:#000" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
      <div class="modal-dialog">
        <div class="loginmodal-container">
          <h1>登录Cikii</h1><br>
          <form id="loginForm">
            <input type="text" name="username" placeholder="用户名">
            <input type="password" name="password" placeholder="密码">
            <input type="submit" name="login" class="login loginmodal-submit" value="Login">
          </form>
          <div class="login-help">
            <a href="http://beyond.cikii.com/user/register/edit">注册新用户</a> - <a href="#">找回密码</a>
          </div>
        </div>
      </div>
    </div>

  </div> <!-- container -->
</div> <!-- header -->
<hr>

<!-- Main component for a primary marketing message or call to action -->
  <!-- umeditor -->
  <div class="container">

    <form name="addPostForm" id="addPostForm" class="form-horizontal">
      <div class="form-group">
        <div class="col-sm-10">
          <input id="postTitle" name="title" type="text/plain" class="form-control" placeholder="在此输入文章标题"></input>
        </div>
        <label class="col-sm-2 control-label">文章标题不要超过30字</label>
      </div>
      <!-- 文章内容 -->
      <div id="file" name="postContent" type="text/plain">

      </div>
      <!-- 文章内容 -->
      <div class="form-group">
        <label for="postCategory" class="col-sm-1 control-label">选择分类</label>

        <div class="col-sm-11" id="postCategory">
          <span class="button-checkbox">
            <button type="button" class="btn btn-xs" data-color="info">原创</button>
            <input type="checkbox" class="hidden" name="postType[]" value="original" checked />
          </span>
          <span class="button-checkbox">
            <button type="button" class="btn btn-xs" data-color="info">即兴</button>
            <input type="checkbox" class="hidden" name="postType[]" value="jixing" />
          </span>
          <span class="button-checkbox">
            <button type="button" class="btn btn-xs" data-color="info">清新</button>
            <input type="checkbox" class="hidden" name="postType[]" value="fresh" />
          </span>
          <span class="button-checkbox">
            <button type="button" class="btn btn-xs" data-color="info">经典</button>
            <input type="checkbox" class="hidden" name="postType[]" value="classic" />
          </span>
          <span class="button-checkbox">
            <button type="button" class="btn btn-xs" data-color="info">怀旧</button>
            <input type="checkbox" class="hidden" name="postType[]" value="reminiscence"/>
          </span>
          <span class="button-checkbox">
            <button type="button" class="btn btn-xs" data-color="info">2U</button>
            <input type="checkbox" class="hidden" name="postType[]" value="foryou"/>
          </span>
		<!--
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-success active">
              <input type="radio" name="options" id="option1" autocomplete="off" value="public" checked> 公开
            </label>
            <label class="btn btn-success">
              <input type="radio" name="options" id="option2" autocomplete="off" value="private"> 不公开
            </label>
          </div>
		-->
          <input type="hidden" name="category" value="<?php echo $_SERVER['HTTP_HOST']; ?>">


        </div>
      </div> <!-- 分类 -->


      <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
           <button id="submit" type="submit" class="btn btn-success pull-right">发表</button>
         </div>
      </div>

    </form>
  </div>

<script src="<?php echo __STATIC_FILE__;?>/js/jssor.slider.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/jquery.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/bootstrap.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/validator.js"></script>
<!--
<script type="text/javascript" charset="utf-8" src="http://beyond.cikii.com/umeditor/umeditor.min.js" ></script>
<script type="text/javascript" charset="utf-8" src="http://beyond.cikii.com/umeditor/umeditor.config.js"></script>
-->
<script type="text/javascript" charset="utf-8" src="http://beyond.cikii.com/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="http://beyond.cikii.com/ueditor/ueditor.all.min.js" ></script>
<script type="text/javascript" charset="utf-8" src="http://beyond.cikii.com/ueditor/ueditor.parse.min.js" ></script>
<script src="<?php echo __STATIC_FILE__;?>/js/layer.js"></script>
<script type="text/javascript">
  var ue = UE.getEditor('file', {
    autoHeight: false
  });
</script>
<script type="text/javascript">

// bootstrap  button 变选择框
$(function () {
    $('.button-checkbox').each(function () {

        // Settings
        var $widget = $(this),
            $button = $widget.find('button'),
            $checkbox = $widget.find('input:checkbox'),
            color = $button.data('color'),
            settings = {
                on: {
                    icon: 'glyphicon glyphicon-check'
                },
                off: {
                    icon: 'glyphicon glyphicon-unchecked'
                }
            };

        // Event Handlers
        $button.on('click', function () {
            $checkbox.prop('checked', !$checkbox.is(':checked'));
            $checkbox.triggerHandler('change');
            updateDisplay();
        });
        $checkbox.on('change', function () {
            updateDisplay();
        });

        // Actions
        function updateDisplay() {
            var isChecked = $checkbox.is(':checked');

            // Set the button's state
            $button.data('state', (isChecked) ? "on" : "off");

            // Set the button's icon
            $button.find('.state-icon')
                .removeClass()
                .addClass('state-icon ' + settings[$button.data('state')].icon);

            // Update the button's color
            if (isChecked) {
                $button
                    .removeClass('btn-default')
                    .addClass('btn-' + color + ' active');
            }
            else {
                $button
                    .removeClass('btn-' + color + ' active')
                    .addClass('btn-default');
            }
        }

        // Initialization
        function init() {

            updateDisplay();

            // Inject the icon if applicable
            if ($button.find('.state-icon').length == 0) {
                $button.prepend('<i class="state-icon ' + settings[$button.data('state')].icon + '"></i> ');
            }
        }
        init();
    });
});


$(function(){
  $("#addPostForm").submit(function(event){
    event.preventDefault(); /* 阻止url变化 */

    var postTitle = document.getElementById("postTitle").value;
    postTitle = postTitle.replace(/(^\s*)|(\s*$)/g, "");
    if ( postTitle=="" || postTitle==null) {
      alert('写个标题呗.');
      return;
    }



    var hasContents = UE.getEditor('file').hasContents();
    if( false == hasContents) {
        alert('请输入内容后提交');
        return;
    }
    var ContentTxt = UE.getEditor('file').getContentTxt();
    ContentTxt = ContentTxt.replace(/(^\s*)|(\s*$)/g, "");
    if ( ContentTxt=="" || ContentTxt==null) {
      alert('啥也没写啊.');
      return;
    }

    var ContentTxt = UE.getEditor('file').getContentTxt();
    if ( 20  >= ContentTxt.length ) {
      alert('多写几个字呗');
      return;
    }

    layer.load(1);
    $.ajax({
      url: "http://beyond.cikii.com/blog/home/addPost",
      method: "POST",
      data: $("#addPostForm").serialize(),
      dataType: "json",
      success: function(data) {
        if (data.ret == "success") {
          layer.closeAll('loading');
          layer.msg('恭喜,注册成功',
            {
              time: 2000,
            }
          );
          window.location.href = "http://beyond.cikii.com/blog/home/list/postId/"+ data.postId;
        }
      },
      error: function(data) {
        layer.closeAll('loading');
        layer.msg('对不起,注册失败',
          {
            time: 2000,
          }
        );
      }
    });
  });
});

</script>
</body>
</html>
