<!DOCTYPE html>
<html lang="zh_CN">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="/faviconcompress.ico" sizes="16x16 32x32" type="image/vnd.microsoft.icon">
<title></title>
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/base.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/blog.css">
<link rel="stylesheet" href="<?php echo __STATIC_FILE__;?>/css/comment.css">
<script src="<?php echo __STATIC_FILE__;?>/js/respond.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/html5shiv.min.js"></script>


</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" >
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><h2>BEYOND</h2></a>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">博客</a></li>
          <li><a href="#">活动报名</a></li>
          <li><a href="#">Beyond 新闻</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="../navbar/">我的博客</a></li>
          <li><a href="../navbar/">我的活动</a></li>
          <li><a href="../navbar/">用户</a></li>
          <li><a href="../navbar/">退出</a></li>
        </ul>
      </div> <!-- nav-collapse -->
    </div>
  </nav>

<!-- Main component for a primary marketing message or call to action -->
  <div class="context">
    <div class="container">
      <h3> <?php $post_obj = json_decode($post); echo ($post_obj->title); ?> </h3>
      <hr></hr>
      <h5><?php $t=$post_obj->ctime; echo(date("Y-m-d",$t)); echo " --- \t @".$nickname ?> </h5></br>
      <hr></hr>

    </div> <!-- blog正文 container -->
  </div>


  <hr></hr>

  <div class="comment">
    <div class="container">
      <div class="media">
        <div class="media-left media-middle">
          <a href="#">
            <img class="media-object" src="..." alt="...">
          </a>
        </div>
        <div class="media-body">
        <form id="comment">
            <textarea class="form-control" rows="3"></textarea>
            <button class="btn btn-info pull-right btn-submit" type="submit">&nbsp;&nbsp;发布&nbsp;&nbsp;</button>
        </form>
        </div>
      </div>
    </div> <!-- 评论 container -->
  </div>

   <div class="modal fade" style="display:none; color:#000" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModal    Label" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
      <div class="loginmodal-container">
        <h1>登录Cikii</h1><br>
        <form id="loginForm">
          <input type="text" name="username" placeholder="用户名">
          <input type="password" name="password" placeholder="密码">
          <input type="submit" name="login" class="login loginmodal-submit" value="Login">
        </form>
        <div class="login-help">
          <a href="http://beyond.cikii.com/user/register/edit">注册新用户</a> - <a href="#">找回密码</a>
        </div>
      </div>
    </div>
   </div>


<script src="<?php echo __STATIC_FILE__;?>/js/jssor.slider.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/jquery.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/bootstrap.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/validator.js"></script>
<!--
<script src="<?php echo __STATIC_FILE__;?>/js/lang/zh-cn/zh-cn.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/umeditor.min.js"></script>
<script src="<?php echo __STATIC_FILE__;?>/js/umeditor.config.js"></script>
-->
<script src="<?php echo __STATIC_FILE__;?>/js/layer.js"></script>
<script type="text/javascript">
  // var um = UM.getEditor('file');
  var userId = "<?php echo $userId ?>";
  $(function(){
    $("#upId").click(function(event) {
      event.preventDefault();
      if(userId=="" || userId==null) {
        $('#login-modal').modal();
      }else {
        $.ajax({
          method: "GET",
          dataType: "json",
          url: "http://beyond.cikii.com/blog/home/up/userId/<?=$userId?>/postId/<?=$post_obj->postId?>",
          complete: function(data) {
            var returnText = eval("(" + data.responseText + ")" );
            if (data.status == 200 && returnText.ret == "success") {
              $(".badgeUp").html(returnText.upNum);
            } 
          } // complete
        }); // ajax
      } // else
    }); // upclick

    $("#downId").click(function(event) {
      event.preventDefault();
      if(userId=="" || userId==null) {
        $('#login-modal').modal();
      }else {
        $.ajax({
          method: "GET",
          dataType: "json",
          url: "http://beyond.cikii.com/blog/home/down/userId/<?=$userId?>/postId/<?=$post_obj->postId?>",
          complete: function(data) {
            var returnText = eval("(" + data.responseText + ")" );
            if (data.status == 200 && returnText.ret == "success") {
              $(".badgeDown").html(returnText.downNum);
            } 
          } // complete
        }); // ajax
      } // else
    }); // downclick
}); // click

$(function(){
    $("#loginForm").submit(function(event){
      event.preventDefault(); /* 阻止url变化 */
      layer.load(1);
      $.ajax({
        url: "http://beyond.cikii.com/user/index/login",
        method: "POST",
        data: $("#loginForm").serialize(),
        dataType: "json",
        /*
        success: function(data) {
          if (data.ret == "success") {
			      window.location.href = "http://beyond.cikii.com"
          }
        },
        error: function(data) {
          layer.closeAll('loading');
          layer.msg('用户名或密码错误,登录失败', 
                      {
                        time: 2000,
                      }
                   );
        },
        */
        complete: function(data) {
          var returnText = eval("(" + data.responseText + ")" );
          if (data.status == 200 && returnText.ret == "success") {
			      window.location.href = window.location .href;
          } else {
            layer.closeAll('loading');
            layer.msg('用户名或密码错误,登录失败', 
                      {
                        time: 2000,
                      }
                   );
                 }
        }
      });
    });
  });


</script>
</body>
</html>
