server:
  host: localhost
  post: 8000
  readtimeout: 50
  writetimeout: 50

mongodb:
  # mongodbURI: "mongodb+srv://cikii:1Fys0F1vzWjKkKGE@cluster0-oqjxi.azure.mongodb.net/test?retryWrites=true&w=majority"
  mongodbURI: "mongodb://10.232.220.42:8017"
  db: cikii

  
